//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:2.0.50727.3603
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServer
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Wiadomosc", Namespace = "http://schemas.datacontract.org/2004/07/WcfServer")]
    public partial class Wiadomosc : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string Do_kogoField;

        private string NameField;

        private int OpcjeField;

        private string TrescField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Do_kogo
        {
            get
            {
                return this.Do_kogoField;
            }
            set
            {
                this.Do_kogoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Opcje
        {
            get
            {
                return this.OpcjeField;
            }
            set
            {
                this.OpcjeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tresc
        {
            get
            {
                return this.TrescField;
            }
            set
            {
                this.TrescField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IServer", CallbackContract = typeof(IServerCallback), SessionMode = System.ServiceModel.SessionMode.Required)]
public interface IServer
{

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IServer/Connect")]
    void Connect(string name);

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IServer/SayToServer")]
    void SayToServer(WcfServer.Wiadomosc msg);

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, IsTerminating = true, Action = "http://tempuri.org/IServer/Disconnect")]
    void Disconnect(string name);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IServerCallback
{

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IServer/SayToClient")]
    void SayToClient(WcfServer.Wiadomosc msg);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IServerChannel : IServer, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class ServerClient : System.ServiceModel.DuplexClientBase<IServer>, IServer
{

    public ServerClient(System.ServiceModel.InstanceContext callbackInstance) :
        base(callbackInstance)
    {
    }

    public ServerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) :
        base(callbackInstance, endpointConfigurationName)
    {
    }

    public ServerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) :
        base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }

    public ServerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }

    public ServerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(callbackInstance, binding, remoteAddress)
    {
    }

    public void Connect(string name)
    {
        base.Channel.Connect(name);
    }

    public void SayToServer(WcfServer.Wiadomosc msg)
    {
        base.Channel.SayToServer(msg);
    }

    public void Disconnect(string name)
    {
        base.Channel.Disconnect(name);
    }
}
